-- Migration: SQLite to PostgreSQL (Supabase)
-- Tables are ordered by foreign key dependencies

-- ============================================
-- Tables with no dependencies
-- ============================================

create table categories
(
    id          integer generated by default as identity primary key,
    name        text,
    description text
);

create table places
(
    id       integer generated by default as identity primary key,
    name     text,
    location text,
    country  text,
    city text
);

create table reviewers
(
    id   integer generated by default as identity primary key,
    name text
);

-- ============================================
-- Tables with dependencies
-- ============================================

create table products
(
    id          integer generated by default as identity primary key,
    name        text,
    category_id integer
        references categories (id)
);

create table features
(
    id         integer generated by default as identity primary key,
    name       text,
    product_id integer
        references products (id)
);

create table reviews
(
    id          integer generated by default as identity primary key,
    place_id    integer not null
        references places (id),
    product_id  integer not null
        references products (id),
    reviewer_id integer not null
        references reviewers (id),
    timestamp   timestamptz,
    comments    text
);

create table stars
(
    id         integer generated by default as identity primary key,
    feature_id integer not null
        references features (id),
    review_id  integer not null
        references reviews (id),
    value      real not null
);
